resume: 'weights/motrv2_dancetrack.pth'
meta_arch:  'motr'
dataset_file:  e2e_dance
with_box_refine: False
sample_mode: 'random_interval'
sample_interval: 10
sampler_lengths: 5
fp_ratio: 10
query_interaction_layer: 'QIMv2'
query_denoise: 0.05
score_threshold: 0.3
update_score_threshold: 0.3
miss_tolerance: 20
device: 'cuda: 0'
random_drop: 0
hidden_dim: 256
backbone: 'resnet50'
dim_feedforward: 1024
position_embedding: 'sine'
position_embedding_scale: 6.283185307179586
lr_backbone_names: 'backbone.0'
lr_backbone: 2.0e-5
save_period: 50
two_stage: False
accurate_ratio: False
frozen_weights: null
num_anchors: 1
enable_fpn: False
dilation:  False
num_feature_levels:  4
enc_layers:  6
dec_layers:  6
dropout:  0.1
nheads :  8
num_queries:  10
dec_n_points:  4
enc_n_points:  4
decoder_cross_self:  False
sigmoid_attn: False
crop: False
cj: False
extra_track_attn: False
max_size: 1333
val_width: 800
filter_ignore: False
append_crowd: True
masks: False
output_dir: '/root/Hoang/Video_Analysis/Video-Analysis/VideoAnalysis/track/MOTR'
aux_loss: True
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2
mask_loss_coef: 1
dice_loss_coef: 1
cls_loss_coef: 2
bbox_loss_coef: 5
giou_loss_coef: 2
focal_alpha: 0.25
remove_difficult: False
eval: True
vis: False
num_workers: 2
cache_mode: False
fp_ratio: 0.3
merger_dropout: 0.1
update_query_pos: False
sampler_steps: null
sampler_lengths: [5]
exp_name: 'submit'
memory_bank_score_thresh: 0.0
memory_bank_len: 4
memory_bank_type: null
memory_bank_with_self_attn: False
use_checkpoint: True
shard_id: 0
num_shards: 1
init_method: null
opts: null
device : cuda:0